# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: arith
synopsis: A new haskell project.
description: arith is a new haskell project.
version: '0.1.0'
category: Other
maintainer: Nikolas Vourlakis
github: Archimidis/arith
license: MIT
library:
  source-dirs: src
  dependencies:
  - base
  - parsec
  - pretty

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

executables:
  arith:
    source-dirs: app
    main: Main.hs
    dependencies:
    - base
    - arith
    - parsec
    - haskeline
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  arith-test-suite:
    source-dirs: test
    main: Main.hs
    dependencies:
    - base
    - arith
    - HUnit
    - tasty
    - tasty-hunit
    - hedgehog
    - tasty-hedgehog
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
